apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pk5r6avni-python 
  janus-idp.io/tekton: pk5r6avni-python
  backstage.io/kubernetes-id: pk5r6avni-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pk5r6avni-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml