apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pk5r6avni-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pk5r6avni-python 
  name: pk5r6avni-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pk5r6avni-python 
